package bingoclient2;

import org.jdesktop.xswingx.PromptSupport;
import bingoserializables.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fikri
 */
public class CreateRoomF extends javax.swing.JFrame {

    
    LobbyFrame lobbyFrame;
    /**
     * Creates new form CreateRoomF
     */
    public CreateRoomF(LobbyFrame lf) {
        initComponents();
        lobbyFrame = lf;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelRoomName = new javax.swing.JLabel();
        jTextFieldRoomName = new javax.swing.JTextField();
        jLabelMaxPlayer = new javax.swing.JLabel();
        jComboBoxMaxPlayer = new javax.swing.JComboBox();
        jLabelGameMode = new javax.swing.JLabel();
        jComboBoxGameMode = new javax.swing.JComboBox();
        jLabelTileSize = new javax.swing.JLabel();
        jComboBoxTileSize = new javax.swing.JComboBox();
        jButtonCreate = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitle.setText("Create Room");

        jLabelRoomName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRoomName.setText("Room Name");

        jLabelMaxPlayer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMaxPlayer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMaxPlayer.setText("Max Player");

        jComboBoxMaxPlayer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "5", "6", "7", "8" }));
        jComboBoxMaxPlayer.setToolTipText("");

        jLabelGameMode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGameMode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelGameMode.setText("Game Mode");

        jComboBoxGameMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal mode", "Suprise mode" }));
        jComboBoxGameMode.setToolTipText("");

        jLabelTileSize.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTileSize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTileSize.setText("Tile Size");

        jComboBoxTileSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "6", "7" }));
        jComboBoxTileSize.setToolTipText("");

        jButtonCreate.setText("Create");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMaxPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRoomName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelGameMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTileSize, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxMaxPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTileSize, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitle)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRoomName)
                    .addComponent(jTextFieldRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaxPlayer)
                    .addComponent(jComboBoxMaxPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGameMode)
                    .addComponent(jComboBoxGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTileSize)
                    .addComponent(jComboBoxTileSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonCreate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PromptSupport.setPrompt("Enter room name", jTextFieldRoomName);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        try {
            CreateRoom cr = new CreateRoom();
            cr.id = jTextFieldRoomName.getText();
            cr.bingoSize = jComboBoxTileSize.getSelectedIndex() + 5;
            cr.maxPlayer = jComboBoxMaxPlayer.getSelectedIndex() + 4;
            cr.normalMode = jComboBoxGameMode.getSelectedIndex() == 0;
            cr.host = ClientGlobals.id;
            ClientGlobals.os.writeObject(cr);
            ClientGlobals.os.flush();
            this.setVisible(false);
            lobbyFrame.setVisible(false);
            BingoFrame2 bf2 = new BingoFrame2(cr.bingoSize);
            DefaultListModel lm = new DefaultListModel();
            lm.addElement(ClientGlobals.id);
            bf2.setPlayerListModel(lm);
            bf2.setVisible(true);
            ClientGlobals.activeRoomID = cr.id;
            ClientGlobals.gameFrame = bf2;
        } catch (IOException ex) {
            Logger.getLogger(CreateRoomF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JComboBox jComboBoxGameMode;
    private javax.swing.JComboBox jComboBoxMaxPlayer;
    private javax.swing.JComboBox jComboBoxTileSize;
    private javax.swing.JLabel jLabelGameMode;
    private javax.swing.JLabel jLabelMaxPlayer;
    private javax.swing.JLabel jLabelRoomName;
    private javax.swing.JLabel jLabelTileSize;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldRoomName;
    // End of variables declaration//GEN-END:variables
}
