/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesignSource;

import javax.swing.JList;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author fikri
 */
public class LobbyFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    public LobbyFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setBounds(674, 51, 156, 360);
        jListPlayer = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setBounds(654, 51, 2, 318);
        jLabelPlayer = new javax.swing.JLabel();
        jLabelPlayer.setBounds(691, 11, 125, 29);
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane3.setBounds(10, 422, 166, 160);
        jTextFiledWispName = new javax.swing.JTextField();
        jTextFiledWispName.setBounds(10, 589, 88, 20);
        jTextFieldChat = new javax.swing.JTextField();
        jTextFieldChat.setBounds(104, 589, 640, 20);
        jButtonSendChat = new javax.swing.JButton();
        jButtonSendChat.setBounds(750, 588, 80, 23);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 640));
        setResizable(false);

        jListPlayer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListPlayer.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Player 1", "Player 2", "Player 3", "Player 4", "Player 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListPlayer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListPlayer.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jListPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPlayerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListPlayerMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListPlayer);

        jLabelPlayer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPlayer.setText("Player List");
        jLabelPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPlayerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelPlayerMousePressed(evt);
            }
        });

        jTextFiledWispName.setText("Whisper");
        jTextFiledWispName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFiledWispNameActionPerformed(evt);
            }
        });

        jTextFieldChat.setText("Chat");

        jButtonSendChat.setText("Send");
        getContentPane().setLayout(null);
        getContentPane().add(jScrollPane2);
        getContentPane().add(jScrollPane1);
        getContentPane().add(jLabelPlayer);
        getContentPane().add(jScrollPane3);
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3.setViewportView(jTextArea1);
        
                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
        getContentPane().add(jTextFiledWispName);
        getContentPane().add(jTextFieldChat);
        getContentPane().add(jButtonSendChat);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListPlayerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPlayerMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jListPlayerMousePressed

    private void jListPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPlayerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListPlayerMouseClicked

    private void jLabelPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlayerMouseClicked
        // TODO add your handling code here:
        jListPlayer.clearSelection();
        jListPlayer.repaint();
    }//GEN-LAST:event_jLabelPlayerMouseClicked

    
    private void jTextFiledWispNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFiledWispNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFiledWispNameActionPerformed

    private void jLabelPlayerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlayerMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPlayerMousePressed
    private javax.swing.JButton jButtonSendChat;
    private javax.swing.JLabel jLabelPlayer;
    private javax.swing.JList jListPlayer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldChat;
    private javax.swing.JTextField jTextFiledWispName;
    // End of variables declaration//GEN-END:variables
}
